* prettier-org
A minor mode that runs [[https://prettier.io/docs/en/install.html][prettier]] on save in src org-mode blocks.

** Installation

*** with use-package and straight:

#+begin_src elisp
(use-package prettier-org
  :straight (:repo "KarimAziev/prettier-org" :type git :host github)
  :commands (prettier-org-format prettier-org-format-all-src-blocks)
  :hook (org-mode . prettier-org-mode))
#+end_src
*** Manually

Download repository and add it to your load path.

#+begin_src elisp
(require 'prettier-org)
(require 'org)

(add-hook 'org-mode 'prettier-org-mode)

#+end_src

** Commands
+ =prettier-org-mode=

Turn on/off a minor mode that runs prettier on save when point is inside body of src block.

+ =prettier-org-format-all-src-blocks= (&optional file)

Format all src blocks in FILE or current buffer.

+ =prettier-org-format= (&optional argument)

If language of src block found in ~prettier-org-src-parsers-alist~, format it.
Common flags and options for prettier can be customized via ~prettier-org-args~. Interactively, with prefix argument, read prettier options in minibuffer.

** Customization

+ =prettier-org-args=
List of common flags and arguments to send to prettier, except option --parser, which should be specified in the variable ~prettier-org-src-parsers-alist~.

+ =prettier-org-src-parsers-alist=
Alist of org src languages and corresponding prettier parser.
